package com.netposa.rom.dao.user;

import java.util.List;

import com.netposa.rom.model.user.DbUser;
import com.netposa.rom.model.user.DbUserExample;
import org.apache.ibatis.annotations.Param;

public interface DbUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Aug 20 20:22:24 CST 2018
     */
    long countByExample(DbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Aug 20 20:22:24 CST 2018
     */
    int deleteByExample(DbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Aug 20 20:22:24 CST 2018
     */
    int insert(DbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Aug 20 20:22:24 CST 2018
     */
    int insertSelective(DbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Aug 20 20:22:24 CST 2018
     */
    List<DbUser> selectByExample(DbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Aug 20 20:22:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") DbUser record, @Param("example") DbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Aug 20 20:22:24 CST 2018
     */
    int updateByExample(@Param("record") DbUser record, @Param("example") DbUserExample example);
}